apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{.Values.applicationManifest.name}}
  namespace: {{.Values.applicationManifest.namespace}}
  labels:
    app: {{.Values.applicationManifest.app}}
spec:
  replicas: {{.Values.applicationManifest.replicas}}
  selector:
    matchLabels: 
      app: {{.Values.applicationManifest.app}}
  template:
    metadata:
      labels:
        app: {{.Values.applicationManifest.app}}
    spec:
      containers:
      - name: {{.Values.applicationManifest.name}}
        image: {{.Values.applicationManifest.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 80m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata: 
  name: {{.Values.applicationManifest.name}}
  namespace: {{.Values.applicationManifest.namespace}}
spec:
  selector:
    app: {{.Values.applicationManifest.app}}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.applicationManifest.name}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: {{.Values.applicationManifest.namespace}}  
spec:
  rules:
  - host: www.exapmle-test.com
    http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: {{.Values.applicationManifest.name}}
            port: 
              number: 80
        path: /nginx(/|$)(.*)    
  ingressClassName: nginx
