apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-example-deployment
  namespace: default
  labels:
    app: nginx-example
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - name: nginx-example
        image: 232452606882.dkr.ecr.us-east-1.amazonaws.com/nginx-example:GITCOMMIT
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 80m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata: 
  name: nginx-example-service
  namespace: default
spec:
  selector:
    app: nginx-example
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  namespace: default  
spec:
  rules:
  - host: www.exapmle-test.com
    http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx-example-service
            port: 
              number: 80
        path: /nginx(/|$)(.*)    
  ingressClassName: nginx
